UserName = input("What is your name?: ")
UserAge = input("How old are you?: ")
UserSity = input("Where are you live?: ")
print("This is", UserName)
print("It is ", UserAge)
print("She lives in ", UserSity)
